name: CI-Checks

on:
  pull_request:
    # Ensures pull requests to development meet appropriate code coverage before merge.
    branches: [ Development ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "merge-feature"
  merge-feature:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout this branch from github
      - name: Step 1 - Checkout branch from Github
        uses: actions/checkout@v2
      
      # Setup JDK environment, version adopt 16
      - name: Step 2 - Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 16
          distribution: adopt
          
      # Run maven's verify with jacoco to ensure 90% model and view code coverage.
      - name: Step 3 - Test project(s) with Maven
        run: |
          echo Testing Weather App Gui
          cd code
          cd weatherapp_gui
          mvn --batch-mode --update-snapshots clean verify
          cd ..
          
          echo Testing Weather App Service
          cd weatherapp_service
          mvn --batch-mode --update-snapshots clean verify
          cd ..
          
          echo Testing Weather App Shared
          cd weatherapp_shared
          mvn --batch-mode --update-snapshots clean verify
          cd ..
